# Generated by Django 5.0.4 on 2024-12-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_co2_emission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economic_forecast',
            name='year_2065',
        ),
        migrations.RemoveField(
            model_name='economic_forecast',
            name='year_2075',
        ),
        migrations.RemoveField(
            model_name='economic_forecast',
            name='year_2085',
        ),
        migrations.RemoveField(
            model_name='economic_forecast',
            name='year_2095',
        ),
    ]
