# Generated by Django 5.0.4 on 2024-12-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_economic_forecast_year_2065_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2020',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2025',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2030',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2035',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2040',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2045',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2050',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2055',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2060',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2070',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2080',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2090',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='economic_forecast',
            name='year_2100',
            field=models.FloatField(default=0),
        ),
    ]
